services:
  phpfpm:
    image: itkdev/php${PHP_VERSION:-7.4}-fpm:latest
    user: ${COMPOSE_USER:-deploy}
    environment:
      - PHP_XDEBUG=${PHP_XDEBUG:-0}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-0.0.0.0}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/app
