env:
    COMPOSE_USER: runner

on: pull_request
name: Review
jobs:
  test-composer-install:
    runs-on: ubuntu-latest
    strategy: &strategy
      fail-fast: false
      matrix:
        php:
          - '7.4'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
    env: &env
        PHP_VERSION: ${{ matrix.php }}
    name: Validate composer (${{ matrix.php }})
    steps:
      - uses: actions/checkout@v7

      - name: Validate composer files
        run: docker compose run --rm phpfpm composer validate

      - name: Composer install
        run: docker compose run --rm phpfpm composer install

  unit_tests:
    runs-on: ubuntu-latest
    strategy: *strategy
    env: *env
    name: Unit tests (${{ matrix.php }})
    steps:
      - uses: actions/checkout@v7

      - name: Composer install
        run: docker compose run --rm phpfpm composer install

      - name: Unit tests
        run: docker compose run --rm phpfpm php vendor/bin/phpunit --coverage-clover=coverage/unit.xml

  phpcsfixer:
    runs-on: ubuntu-latest
    strategy: *strategy
    env: *env
    name: Coding style fixer (${{ matrix.php }})
    steps:
      - uses: actions/checkout@v7

      - name: Composer install
        run: docker compose run --rm phpfpm composer install

      - name: Unit tests
        run: docker compose run --rm phpfpm composer check-coding-standards

  psalm:
    runs-on: ubuntu-latest
    strategy: *strategy
    env: *env
    name: Static analysis (${{ matrix.php }})
    steps:
      - uses: actions/checkout@v7

      - name: Composer install
        run: docker compose run --rm phpfpm composer install

      - name: Running analysis
        run: docker compose run --rm phpfpm composer psalm
